require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ComponentsController do

  def mock_component(stubs={})
    @mock_component ||= mock_model(Component, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all components as @components" do
      Component.stub(:all) { [mock_component] }
      get :index
      assigns(:components).should eq([mock_component])
    end
  end

  describe "GET show" do
    it "assigns the requested component as @component" do
      Component.stub(:find).with("37") { mock_component }
      get :show, :id => "37"
      assigns(:component).should be(mock_component)
    end
  end

  describe "GET new" do
    it "assigns a new component as @component" do
      Component.stub(:new) { mock_component }
      get :new
      assigns(:component).should be(mock_component)
    end
  end

  describe "GET edit" do
    it "assigns the requested component as @component" do
      Component.stub(:find).with("37") { mock_component }
      get :edit, :id => "37"
      assigns(:component).should be(mock_component)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created component as @component" do
        Component.stub(:new).with({'these' => 'params'}) { mock_component(:save => true) }
        post :create, :component => {'these' => 'params'}
        assigns(:component).should be(mock_component)
      end

      it "redirects to the created component" do
        Component.stub(:new) { mock_component(:save => true) }
        post :create, :component => {}
        response.should redirect_to(component_url(mock_component))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved component as @component" do
        Component.stub(:new).with({'these' => 'params'}) { mock_component(:save => false) }
        post :create, :component => {'these' => 'params'}
        assigns(:component).should be(mock_component)
      end

      it "re-renders the 'new' template" do
        Component.stub(:new) { mock_component(:save => false) }
        post :create, :component => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested component" do
        Component.stub(:find).with("37") { mock_component }
        mock_component.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :component => {'these' => 'params'}
      end

      it "assigns the requested component as @component" do
        Component.stub(:find) { mock_component(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:component).should be(mock_component)
      end

      it "redirects to the component" do
        Component.stub(:find) { mock_component(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(component_url(mock_component))
      end
    end

    describe "with invalid params" do
      it "assigns the component as @component" do
        Component.stub(:find) { mock_component(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:component).should be(mock_component)
      end

      it "re-renders the 'edit' template" do
        Component.stub(:find) { mock_component(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested component" do
      Component.stub(:find).with("37") { mock_component }
      mock_component.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the components list" do
      Component.stub(:find) { mock_component }
      delete :destroy, :id => "1"
      response.should redirect_to(components_url)
    end
  end

end
